### ISSUE TITLE
How to deal with aug vs non aug trees

### ISSUE THREAD

**Issue by EMventura** [meraxes-devs/meraxes#5]
As more new members start to use (run/develop) meraxes, we should aim for a better way to handle aug and non-aug trees, which have different formats. Currently, we need to have two branches to do that. To move forward, there are two ways:

1) Do the same thing to Non-augmented trees, so that we can get rid of variables that are less important (if not completely useless; e.g., Tail; I have a comment in my aug version that goes like // Balu said Tail is always equal to ID... ), replace Lx, Ly, Lz with AngMom, and deal with hubble_h in the tree files directly (e.g., masses). We also need to make sure the variables are given a consistent type (e.g. unsigned long ForestID vs long ForestID);

2) Have TreesID to deal with aug and non-aug, similar to what we are doing with the gbptrees.

As @qyx268 said, probably option 2 is more straightforward even though it will require to duplicate many lines (similarly to what is done with gbp trees vs vr trees), but if you have a stronger opinion for 1 write it here. Once we decide we can organise this new (minor) development.

**Comment by qyx268** [comment]
#6
